version: "3.8"

services:
  
  vs-back:
    build:
      context: ./VueSlavery_back
    networks:
      - vueslavery
    depends_on:
      - mariadb
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      DB_HOST: host.docker.internal
    ports:
      - "5174:5174"

  vs-front:
    build:
      context: ./VueSlavery_front
    networks:
      - vueslavery
    ports:
      - "5173:5173"

  mariadb:
    image: mariadb
    restart: always
    environment: 
      MARIADB_ROOT_HOST: localhost
      MARIADB_ROOT_PASSWORD: test
      MARIADB_DATABASE: VueSlaveryDB
    networks:
      - vueslavery
    ports:
      - "3306:3306"

networks:
  vueslavery:
    driver: bridge
