version: "3.8"

services:
  
  vs-back:
    build:
      context: ./VueSlavery_back
    networks:
      - vueslavery
    depends_on:
      - mariadb
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      DB_HOST: host.docker.internal
    ports:
      - "5174:5174"
    volumes:
      - ./VueSlavery_back:/back
      - /back/node_modules
  vs-front:
    build:
      context: ./VueSlavery_front
    networks:
      - vueslavery
    ports:
      - "5173:5173"
    volumes:
      - ./VueSlavery_front:/front
      - /front/node_modules
  mariadb:
    image: mariadb
    restart: always
    environment: 
      MARIADB_ROOT_PASSWORD: test
      MARIADB_DATABASE: VueSlaveryDB
      MARIADB_USER: myappuser
      MARIADB_PASSWORD: myapppassword
    networks:
      - vueslavery
    ports:
      - "3306:3306"
    volumes:
      - ./backup_data:/var/lib/mysql

networks:
  vueslavery:
    driver: bridge
volumes:
  node_modules:
  backend:
    driver: local
  frontend:
    driver: local
  dbdata:
    driver: local
